INSERT INTO `carmodels` (`id`, `make_id`, `code`, `model`, `model_year`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1322, 67, 'TOYOTA', 'Corolla', NULL, NULL, NULL, NULL),
(1323, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1324, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1325, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1326, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1327, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1328, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1329, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1330, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1331, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1332, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1333, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1334, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1335, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1336, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1337, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1338, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1339, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1340, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1341, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1342, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1343, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1344, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1345, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1346, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),
(1347, 67, 'TOYOTA', 'Other Yugo Models', NULL, NULL, NULL, NULL),

